print(f'Ahoj, jak se jmenuješ...?')
jmeno = input()
print(f'Jaká je tvoje nejcennější vlastnost...?')
vlasnost = input()
print(f'Výsledkem je, že za počítačem je {jmeno} a jeho nejcennější vlastností je {vlasnost}.')
